service: s3-example

provider:
  name: aws
  runtime: nodejs16.x

functions:
  doc-uploader:
    handler: dist/handler.handle
    events:
      - httpApi: PUT /file/{proxy+}
      - httpApi: GET /file/{proxy+}
    role: DocUploadRole
    environment:
      BUCKET: s3example-${opt:stage, 'dev'}
      EXPIRES_IN: 3000 

resources:
  - ${file(resources/s3-bucket.yml)}